---
title: "equipment_analysis"
author: Yi Ning Wong
output: html_document
---

```{r setup, include=FALSE}
remove(list=ls())
library(readxl)
library(tidyverse)
library(ggplot2)
medical <- read_excel("equipment.xlsx")

#combine sizes
medical <- medical %>% mutate(gloves = gloves_s + gloves_m + gloves_l + gloves_xl)
medical <- medical %>% mutate(shoes = shoe_reg + shoe_xl)

#combine types / sizes
medical <- medical %>% mutate(masks = surgical_masks + shield_masks + 
                                n95_masks + offender_masks)

medical <- medical %>% mutate(thermometer = thermometer_ear + thermometer_temporal...17 +
                                thermometer_oral + thermometer_temporal...19)

#Group by Prisons we're looking at
filtered <- medical %>%
  group_by(facility) %>% 
  filter(facility =="East Moline" |
           facility == "Jacksonville" |
           facility == "Menard" | 
           facility == "Logan" |
           facility == "Hill"|
           facility == "Stateville") %>%
  ungroup()

#Shoes and Gloves
ggplot() + geom_point(aes(x=Date, y=test_covid, group=facility), 
                     data = medical,
                     color = alpha("grey", 0.7)) +
  geom_point(aes(x=Date, y=test_covid, color=facility), 
                     data = filtered)



```


```{r filter outliers}

#try without the big outlier
medic_filter <- medical %>% filter(facility != "Decatur" & facility != "Graham" &
                                     facility != "SWICC")


ggplot() + geom_point(aes(x=Date, y=shoes, group=facility), 
                     data = medic_filter,
                     color = alpha("grey", 0.7)) +
  geom_point(aes(x=Date, y=shoes, color=facility), 
                     data = filtered)


## COVID TESTS
ggplot() + geom_point(aes(x=Date, y=test_covid, group=facility), 
                     data = medic_filter,
                     color = alpha("grey", 0.7)) +
  geom_point(aes(x=Date, y=test_covid, color=facility), 
                     data = filtered)

##temperature
ggplot() + geom_point(aes(x=Date, y=thermometer, group=facility), 
                     data = medic_filter,
                     color = alpha("grey", 0.7)) +
  geom_point(aes(x=Date, y=thermometer, color=facility), 
                     data = filtered_two)

##Flu test
ggplot() + geom_point(aes(x=Date, y=test_covid, group=facility), 
                     data = medical,
                     color = alpha("grey", 0.7)) +
  geom_point(aes(x=Date, y=test_flu, color=facility), 
                     data = filtered)

##Masks
ggplot() + geom_point(aes(x=Date, y=masks, group=facility), 
                     data = medic_filter,
                     color = alpha("grey", 0.7)) +
  geom_point(aes(x=Date, y=masks, color=facility), 
                     data = filtered_two)
```
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
remove(list=ls())
library(readxl)
library(tidyverse)
library(ggplot2)
medical <- read_excel("equipment.xlsx")

#combine sizes
medical <- medical %>% mutate(gloves = gloves_s + gloves_m + gloves_l + gloves_xl)
medical <- medical %>% mutate(shoes = shoe_reg + shoe_xl)

#combine types / sizes
medical <- medical %>% mutate(masks = surgical_masks + shield_masks + 
                                n95_masks + offender_masks)

medical <- medical %>% mutate(thermometer = thermometer_ear + thermometer_temporal...17 +
                                thermometer_oral + thermometer_temporal...19)

#Group by Prisons we're looking at
filtered <- medical %>%
  group_by(facility) %>% 
  filter(facility =="East Moline" |
           facility == "Jacksonville" |
           facility == "Menard" | 
           facility == "Logan" |
           facility == "Hill"|
           facility == "Stateville") %>%
  ungroup()

#Shoes and Gloves
ggplot() + geom_point(aes(x=Date, y=test_covid, group=facility), 
                     data = medical,
                     color = alpha("grey", 0.7)) +
  geom_point(aes(x=Date, y=test_covid, color=facility), 
                     data = filtered)


```
